### ISSUE TITLE
Runtime Error in eval_secstr.py

### ISSUE THREAD

**Issue by Chenwf1025** [tbepler/protein-sequence-embedding-iclr2019#20]
`python .\eval_secstr.py 1-mer`
split epoch loss perplexity accuracy
Traceback (most recent call last):
  File ".\eval_secstr.py", line 427, in <module>
    main()
  File ".\eval_secstr.py", line 361, in main
    potentials = model(x).view(x.size(0), -1)
  File "D:\Software\Anaconda\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Software\Anaconda\lib\site-packages\torch\nn\modules\sparse.py", line 126, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "D:\Software\Anaconda\lib\site-packages\torch\nn\functional.py", line 1814, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.IntTensor instead (while checking arguments for embedding)

OS: Windows10, python 3.7.4, pytorch 1.6.0

**Comment by Chenwf1025** [comment]
Ok... Just add `x=x.long()` befor `potentials = model(x).view(x.size(0), -1)` , and `y=y.long()`  after `y = I[y]`would fix the problem.
